using System.Collections;
using System.IO;
using System.Linq;
using System.Text;

namespace TDSView
{
	public class CreateMap
	{
		public ArrayList coordinate;

		public CreateMap()
		{
			coordinate = new ArrayList();
		}

		public void CreateKMLFile(string kmlFileName, string pathDescription)
		{
			Stream stream = File.Create(kmlFileName);
			if (stream == null)
			{
				return;
			}
			StreamWriter streamWriter = new StreamWriter(stream, Encoding.ASCII);
			streamWriter.WriteLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
			streamWriter.WriteLine("<kml xmlns=\"http://www.opengis.net/kml/2.2\" xmlns:gx=\"http://www.google.com/kml/ext/2.2\" xmlns:kml=\"http://www.opengis.net/kml/2.2\" xmlns:atom=\"http://www.w3.org/2005/Atom\">");
			streamWriter.WriteLine("<Document>");
			streamWriter.WriteLine("\t<name>MeinDemoPfad.kml</name>");
			streamWriter.WriteLine("\t<Style id=\"sn_ylw-pushpin\">");
			streamWriter.WriteLine("\t\t<IconStyle>");
			streamWriter.WriteLine("\t\t\t<scale>1.1</scale>");
			streamWriter.WriteLine("\t\t\t<Icon>");
			streamWriter.WriteLine("\t\t\t\t<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
			streamWriter.WriteLine("\t\t\t</Icon>");
			streamWriter.WriteLine("\t\t\t<hotSpot x=\"20\" y=\"2\" xunits=\"pixels\" yunits=\"pixels\"/>");
			streamWriter.WriteLine("\t\t</IconStyle>");
			streamWriter.WriteLine("\t\t<LineStyle>");
			streamWriter.WriteLine("\t\t\t<color>ff0000ff</color>");
			streamWriter.WriteLine("\t\t\t<width>2</width>");
			streamWriter.WriteLine("\t\t</LineStyle>");
			streamWriter.WriteLine("\t</Style>");
			streamWriter.WriteLine("\t<StyleMap id=\"msn_ylw-pushpin\">");
			streamWriter.WriteLine("\t\t<Pair>");
			streamWriter.WriteLine("\t\t\t<key>normal</key>");
			streamWriter.WriteLine("\t\t\t<styleUrl>#sn_ylw-pushpin</styleUrl>");
			streamWriter.WriteLine("\t\t</Pair>");
			streamWriter.WriteLine("\t\t<Pair>");
			streamWriter.WriteLine("\t\t\t<key>highlight</key>");
			streamWriter.WriteLine("\t\t\t<styleUrl>#sh_ylw-pushpin</styleUrl>");
			streamWriter.WriteLine("\t\t</Pair>");
			streamWriter.WriteLine("\t</StyleMap>");
			streamWriter.WriteLine("\t<Style id=\"sh_ylw-pushpin\">");
			streamWriter.WriteLine("\t\t<IconStyle>");
			streamWriter.WriteLine("\t\t\t<scale>1.3</scale>");
			streamWriter.WriteLine("\t\t\t<Icon>");
			streamWriter.WriteLine("\t\t\t\t<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>");
			streamWriter.WriteLine("\t\t\t</Icon>");
			streamWriter.WriteLine("\t\t\t<hotSpot x=\"20\" y=\"2\" xunits=\"pixels\" yunits=\"pixels\"/>");
			streamWriter.WriteLine("\t\t</IconStyle>");
			streamWriter.WriteLine("\t\t<LineStyle>");
			streamWriter.WriteLine("\t\t\t<color>ff0000ff</color>");
			streamWriter.WriteLine("\t\t\t<width>2</width>");
			streamWriter.WriteLine("\t\t</LineStyle>");
			streamWriter.WriteLine("\t</Style>");
			streamWriter.WriteLine("\t<Placemark>");
			streamWriter.WriteLine("\t\t<name>Path generated by TDSView</name>");
			streamWriter.WriteLine("\t\t<description> " + pathDescription + "</description>");
			streamWriter.WriteLine("\t\t<styleUrl>#msn_ylw-pushpin</styleUrl>");
			streamWriter.WriteLine("\t\t<LineString>");
			streamWriter.WriteLine("\t\t\t<tessellate>1</tessellate>");
			streamWriter.WriteLine("\t\t\t<coordinates>");
			char[] separator = new char[1] { '/' };
			bool flag = false;
			if (coordinate.Count > 0)
			{
				string source = (string)coordinate[0];
				if (source.Contains(','))
				{
					flag = true;
				}
			}
			foreach (string item in coordinate)
			{
				string text2 = item;
				if (flag)
				{
					text2 = text2.Replace(",", ".");
				}
				string[] array = text2.Split(separator);
				if (array.Length == 2 && (!array[0].Equals("0.000000") || !array[1].Equals("0.000000")))
				{
					streamWriter.WriteLine("\t\t\t" + array[1] + "," + array[0] + ",0 ");
				}
			}
			streamWriter.WriteLine("\t\t\t</coordinates>");
			streamWriter.WriteLine("\t\t</LineString>");
			streamWriter.WriteLine("\t</Placemark>");
			streamWriter.WriteLine("</Document>");
			streamWriter.WriteLine("</kml>");
			streamWriter.Close();
		}
	}
}
